// Code generated by goctl. DO NOT EDIT!
// Source: post.proto

package server

import (
	"context"

	"go-demo/service/post/rpc/internal/logic"
	"go-demo/service/post/rpc/internal/svc"
	"go-demo/service/post/rpc/types/post"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	post.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------Post-----------------------
func (s *ServiceServer) AddPost(ctx context.Context, in *post.AddPostReq) (*post.AddPostResp, error) {
	l := logic.NewAddPostLogic(ctx, s.svcCtx)
	return l.AddPost(in)
}

func (s *ServiceServer) UpdatePost(ctx context.Context, in *post.UpdatePostReq) (*post.UpdatePostResp, error) {
	l := logic.NewUpdatePostLogic(ctx, s.svcCtx)
	return l.UpdatePost(in)
}

func (s *ServiceServer) DelPost(ctx context.Context, in *post.DelPostReq) (*post.DelPostResp, error) {
	l := logic.NewDelPostLogic(ctx, s.svcCtx)
	return l.DelPost(in)
}

func (s *ServiceServer) GetPostById(ctx context.Context, in *post.GetPostByIdReq) (*post.GetPostByIdResp, error) {
	l := logic.NewGetPostByIdLogic(ctx, s.svcCtx)
	return l.GetPostById(in)
}

func (s *ServiceServer) SearchPost(ctx context.Context, in *post.SearchPostReq) (*post.SearchPostResp, error) {
	l := logic.NewSearchPostLogic(ctx, s.svcCtx)
	return l.SearchPost(in)
}
