// Code generated by goctl. DO NOT EDIT.
package types

type GetPostByIdReq struct {
	Id int64 `json:"id"`
}

type GetPostByIdResp struct {
	Post *Post `json:"post"`
}

type Post struct {
	Id        int64  `json:"id"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
	Title     string `json:"title"`
	Published int64  `json:"published"`
	Desc      string `json:"desc"`
}
